### ISSUE TITLE
shows this error?

### ISSUE THREAD

**Issue by faizahmmd** [ThomasEcalle/app_starter#1]
app_starter -n toto -o io.example -t https://github.com/ThomasEcalle/flappy_template
[INFO] Let's create toto application !
[INFO] Creating flutter project using your current flutter version...
[INFO] Retrieving your template from https://github.com/ThomasEcalle/flappy_template...
[ERROR] Error creating project : ProcessException: The system cannot find the file specified.

  Command: rm -rf C:\Users\faiz/toto/lib
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: rm -rf C:\Users\faiz/toto
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:476:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:619:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      CommandRunner.create (package:app_starter/src/command_runner.dart:204:15)
<asynchronous suspension>
No active package app_starter.

**Comment by ThomasEcalle** [comment]
Hello !

Could you please show the result of the commande `flutter doctor -v` in order to have a little bit of context about your environment ?

Have you well launched the command `flutter pub global activate app_starter` in order to install the package before using it ?
